FROM python:3.6-alpine

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY entrypoint-beat.sh entrypoint.sh
RUN chmod +x entrypoint.sh
COPY stats/ stats/
COPY omnomgram/ omnomgram/
COPY canteens/ canteens/
COPY backend/ backend/

RUN chown nobody /app
USER nobody
CMD ["/app/entrypoint.sh"]
