FROM python:3.6-alpine

WORKDIR /app

RUN apk update
RUN apk add poppler-utils

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY omnomgram/ omnomgram/
COPY canteens/ canteens/
COPY backend/ backend/

USER nobody
CMD celery -A backend.backend worker -l info
