FROM python:3.6-alpine

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY stats/ stats/
COPY omnomgram/ omnomgram/
COPY backend/ backend/
COPY frontend.py frontend.py

USER nobody
CMD python3 frontend.py
