from canteens.cafenero import update_cafenero
from canteens.personalkantine import update_personalkantine
from canteens.singh import update_singh
from canteens.studierendenwerk import update_studierendenwerk

update_cafenero.delay()
update_personalkantine.delay()
update_singh.delay()

update_studierendenwerk.delay(534)
update_studierendenwerk.delay(535)
update_studierendenwerk.delay(527)
update_studierendenwerk.delay(537)
update_studierendenwerk.delay(529)
update_studierendenwerk.delay(271)
update_studierendenwerk.delay(322)
update_studierendenwerk.delay(528)
update_studierendenwerk.delay(531)
update_studierendenwerk.delay(533)
update_studierendenwerk.delay(320)
update_studierendenwerk.delay(319)
update_studierendenwerk.delay(147)
update_studierendenwerk.delay(191)
update_studierendenwerk.delay(367)
update_studierendenwerk.delay(270)
update_studierendenwerk.delay(526)
update_studierendenwerk.delay(532)
update_studierendenwerk.delay(530)
update_studierendenwerk.delay(321)
update_studierendenwerk.delay(323)
update_studierendenwerk.delay(368)
update_studierendenwerk.delay(660)
update_studierendenwerk.delay(542)
update_studierendenwerk.delay(277)
update_studierendenwerk.delay(543)
update_studierendenwerk.delay(726)
update_studierendenwerk.delay(659)
update_studierendenwerk.delay(539)
update_studierendenwerk.delay(540)
update_studierendenwerk.delay(657)
update_studierendenwerk.delay(631)
update_studierendenwerk.delay(541)
update_studierendenwerk.delay(538)
update_studierendenwerk.delay(722)
update_studierendenwerk.delay(658)
update_studierendenwerk.delay(647)
update_studierendenwerk.delay(648)
update_studierendenwerk.delay(1407)
update_studierendenwerk.delay(723)
update_studierendenwerk.delay(724)
update_studierendenwerk.delay(725)
update_studierendenwerk.delay(661)
update_studierendenwerk.delay(721)
update_studierendenwerk.delay(720)
update_studierendenwerk.delay(727)
update_studierendenwerk.delay(728)
update_studierendenwerk.delay(649)
update_studierendenwerk.delay(650)
update_studierendenwerk.delay(632)
